import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";
import Hero from "../components/Hero";
import About from "../components/About";
import Skills from "../components/Skills";
import Tools from "../components/Tools";
import Projects from "../components/Projects";
import Contact from "../components/Contact";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Isaac Kang</title>
        <meta name="description" content="Generated by create next app" />
        <link href="../public/assets/favicon-32x32.png" rel="icon" />
        <link
          href="../public/assets/apple-touch-icon.png"
          rel="apple-touch-icon"
        />
      </Head>
      <Navbar />
      <Hero />
      <About />
      <Skills />
      <Tools />
      <Projects />
      <Contact />
    </div>
  );
}
